directory: ~/Music/beets/

import:
  log: beetslog.txt
  languages: en

embedart:
  remove_art_file: yes

paths:
  default: Albums/$albumartist/$album%aunique{}/$track $title
  singleton: Singles/$artist/$title
  albumtype:soundtrack: Soundtracks/$album/$track $title
  comp: Compilations/$album%aunique{}/$track $title

original_date: yes
# asciify_paths: yes enable if probs

smartplaylist:
  relative_to: ~/Music/beets/
  playlist_dir: ~/Music/beets/Playlists
  playlists:
    - name: beastiechill.m3u
      query: 'playlist:beastiechill'
    - name: countrychicks.m3u
      query: 'playlist:countrychicks'
    - name: freak.m3u
      query: 'playlist:freak'
    - name: funny.m3u
      query: 'playlist:funny'
    - name: singles.m3u
      query: 'singleton:true ^genre:holiday'
    - name: new.m3u
      query: 'added:-1m..' #added in 30 days

convert:
  never_convert_lossy_files: yes

plugins: discogs info fetchart embedart lyrics missing ftintitle smartplaylist convert
